apiVersion: v1
kind: Pod
metadata:
  name: rest-api
  labels:
    app: restapp
spec:
  containers:
  - name: rest-api
    image: docker.io/akashash/rest-api:latest
    ports:
    - containerPort: 8080
